// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caxndzgrszlxzyxqyjyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNheG5kemdyc3pseHp5eHF5anl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTExNjUsImV4cCI6MjA2ODc4NzE2NX0.QBVrWqkscZl64nvvWOMmN7k-k0h7F3yXit1A_pMVv6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});